#!/usr/bin/env python3
"""
gen_failsafe.py — compress src/web/failsafe.html into a C array.

WHAT THIS IS FOR, AND WHAT IT IS NOT
------------------------------------
The failsafe page is the recovery UI: it is what answers when LittleFS has no
/www, which is exactly when the device is broken and you need to reach it. So
it MUST stay inside the firmware image — it cannot live on the filesystem it
exists to repair, and it cannot be fetched from anywhere.

This changes nothing about that. The page is still a `const` array linked into
the binary; it is simply stored gzipped instead of as plain text, and the
browser inflates it. No filesystem, no network, no runtime compression. The
only thing that changes is that the same page occupies ~8 KB of flash instead
of ~27 KB.

WHY A GENERATED HEADER RATHER THAN COMPRESSING AT RUNTIME
--------------------------------------------------------
Compressing at runtime would save no flash at all — the uncompressed text
would still be in the image — and would spend heap and CPU on every request.
The saving only exists if the compressed form is what gets linked.

The generated header IS COMMITTED. PlatformIO regenerates it on every build
via extra_scripts, but the Arduino IDE path (Logger.ino in the project root)
runs no scripts, so a gitignored header would break that build. CI checks the
committed copy still matches the HTML — see tools/check_failsafe.py.

Usage:
    python3 scripts/gen_failsafe.py           # regenerate the header
    python3 scripts/gen_failsafe.py --check   # exit 1 if it is stale
"""
import gzip
import hashlib
import sys
from pathlib import Path

# PlatformIO exec's this file through SCons, where __file__ is NOT defined —
# the same trap tools/deploy_gui.spec documents. env["PROJECT_DIR"] is the
# answer there; __file__ is the answer when run directly or by CI.
try:
    Import("env")  # noqa: F821
    _PIO = True
    ROOT = Path(env["PROJECT_DIR"])  # noqa: F821
except NameError:
    _PIO = False
    ROOT = Path(__file__).resolve().parent.parent

SRC = ROOT / "src" / "web" / "failsafe.html"
OUT = ROOT / "src" / "web" / "FailsafeHtml.h"


def render() -> str:
    raw = SRC.read_bytes()
    # mtime=0 so the output depends only on the input: a rebuild must not
    # produce a different header, or the CI drift check would fail at random
    # and every build would dirty the working tree.
    gz = gzip.compress(raw, compresslevel=9, mtime=0)

    body = []
    for i in range(0, len(gz), 16):
        chunk = gz[i:i + 16]
        body.append("    " + " ".join(f"0x{b:02x}," for b in chunk))

    pct = 100 * (1 - len(gz) / len(raw))
    return f"""// ============================================================================
// src/web/FailsafeHtml.h — GENERATED by scripts/gen_failsafe.py. Do not edit.
//
// Source: src/web/failsafe.html  ({len(raw):,} bytes, sha256 {hashlib.sha256(raw).hexdigest()[:16]})
// Stored: gzip -9                ({len(gz):,} bytes, {pct:.0f}% smaller)
//
// This is the recovery UI, served when LittleFS has no /www — that is, when
// the device is broken and this page is how you reach it. It is linked into
// the firmware image for exactly that reason and is never read from storage.
// Compression does not change where it lives, only how much flash it takes:
// the bytes below are handed to the browser with Content-Encoding: gzip and
// inflated there.
//
// Regenerate with:  python3 scripts/gen_failsafe.py
// ============================================================================
#pragma once

#include <stdint.h>
#include <stddef.h>

static const uint8_t FAILSAFE_HTML_GZ[] PROGMEM = {{
{chr(10).join(body)}
}};

static const size_t FAILSAFE_HTML_GZ_LEN = sizeof(FAILSAFE_HTML_GZ);
"""


def main() -> int:
    if not SRC.is_file():
        print(f"error: {SRC} not found")
        return 2
    text = render()

    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current == text:
            print(f"OK: {OUT.relative_to(ROOT)} matches {SRC.relative_to(ROOT)}")
            return 0
        print(f"FAIL: {OUT.relative_to(ROOT)} is stale.\n"
              f"  {SRC.relative_to(ROOT)} has changed since it was generated.\n"
              f"  Run: python3 scripts/gen_failsafe.py")
        return 1

    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if _PIO:
    main()          # pre-build hook: regenerate before anything compiles
elif __name__ == "__main__":
    sys.exit(main())
