#!/usr/bin/env python3
"""
gen_failsafe.py — compress src/web/failsafe.html into a C array.

WHAT THIS IS FOR, AND WHAT IT IS NOT
------------------------------------
The failsafe page is the recovery UI: it is what answers when LittleFS has no
/www, which is exactly when the device is broken and you need to reach it. So
it MUST stay inside the firmware image — it cannot live on the filesystem it
exists to repair, and it cannot be fetched from anywhere.

This changes nothing about that. The page is still a `const` array linked into
the binary; it is simply stored gzipped instead of as plain text, and the
browser inflates it. No filesystem, no network, no runtime compression. The
only thing that changes is that the same page occupies ~8 KB of flash instead
of ~27 KB.

WHY A GENERATED HEADER RATHER THAN COMPRESSING AT RUNTIME
--------------------------------------------------------
Compressing at runtime would save no flash at all — the uncompressed text
would still be in the image — and would spend heap and CPU on every request.
The saving only exists if the compressed form is what gets linked.

The generated header IS COMMITTED. PlatformIO regenerates it on every build
via extra_scripts, but the Arduino IDE path (Logger.ino in the project root)
runs no scripts, so a gitignored header would break that build. CI runs
`--check` (see .github/workflows/tests.yml) so the committed copy cannot
drift from the HTML.

WHAT --check COMPARES, AND WHY IT IS NOT A BYTE COMPARE
-------------------------------------------------------
It INFLATES the committed header and compares that against failsafe.html.
It deliberately does NOT compare the compressed bytes, because those are not
a property of the input: zlib and zlib-ng emit different (both valid) streams
for the same data at the same level, so a byte compare would fail on a
perfectly correct header purely because CI's Python links a different zlib
than the developer's. What has to hold is that the header inflates to the
current page — that is what is checked, and it is implementation-independent.

For the same reason a build regenerates the header only when the existing one
does NOT inflate to the current HTML. Otherwise a build on a machine with a
different zlib would rewrite a correct header and dirty the working tree.

Usage:
    python3 scripts/gen_failsafe.py           # regenerate if stale
    python3 scripts/gen_failsafe.py --force   # regenerate unconditionally
    python3 scripts/gen_failsafe.py --check   # exit 1 if it is stale
"""
from __future__ import annotations

import gzip
import hashlib
import re
import sys
from pathlib import Path

# PlatformIO exec's this file through SCons, where __file__ is NOT defined —
# the same trap tools/deploy_gui.spec documents. env["PROJECT_DIR"] is the
# answer there; __file__ is the answer when run directly or by CI.
try:
    Import("env")  # noqa: F821
    _PIO = True
    ROOT = Path(env["PROJECT_DIR"])  # noqa: F821
except NameError:
    _PIO = False
    ROOT = Path(__file__).resolve().parent.parent

SRC = ROOT / "src" / "web" / "failsafe.html"
OUT = ROOT / "src" / "web" / "FailsafeHtml.h"


def render() -> str:
    raw = SRC.read_bytes()
    # mtime=0 so the output depends only on the input: a rebuild must not
    # produce a different header, or the CI drift check would fail at random
    # and every build would dirty the working tree.
    gz = gzip.compress(raw, compresslevel=9, mtime=0)

    body = []
    for i in range(0, len(gz), 16):
        chunk = gz[i:i + 16]
        body.append("    " + " ".join(f"0x{b:02x}," for b in chunk))

    pct = 100 * (1 - len(gz) / len(raw))
    return f"""// ============================================================================
// src/web/FailsafeHtml.h — GENERATED by scripts/gen_failsafe.py. Do not edit.
//
// Source: src/web/failsafe.html  ({len(raw):,} bytes, sha256 {hashlib.sha256(raw).hexdigest()[:16]})
// Stored: gzip -9                ({len(gz):,} bytes, {pct:.0f}% smaller)
//
// This is the recovery UI, served when LittleFS has no /www — that is, when
// the device is broken and this page is how you reach it. It is linked into
// the firmware image for exactly that reason and is never read from storage.
// Compression does not change where it lives, only how much flash it takes:
// the bytes below are handed to the browser with Content-Encoding: gzip and
// inflated there.
//
// Regenerate with:  python3 scripts/gen_failsafe.py
// ============================================================================
#pragma once

#include <stdint.h>
#include <stddef.h>
#include <pgmspace.h>   // PROGMEM — do not rely on the includer pulling Arduino.h

static const uint8_t FAILSAFE_HTML_GZ[] PROGMEM = {{
{chr(10).join(body)}
}};

static const size_t FAILSAFE_HTML_GZ_LEN = sizeof(FAILSAFE_HTML_GZ);
"""


_BYTES_RE = re.compile(r"FAILSAFE_HTML_GZ\[\]\s*PROGMEM\s*=\s*\{(.*?)\};", re.S)


def committed_payload() -> bytes:
    """The gzip stream inside the committed header, or b'' if unreadable."""
    if not OUT.is_file():
        return b""
    m = _BYTES_RE.search(OUT.read_text(encoding="utf-8"))
    if not m:
        return b""
    return bytes(int(tok, 16) for tok in re.findall(r"0x([0-9a-fA-F]{2})", m.group(1)))


def committed_is_current() -> tuple[bool, str]:
    """True when the committed header inflates to exactly the current HTML."""
    gz = committed_payload()
    if not gz:
        return False, "no FAILSAFE_HTML_GZ array found (header missing or edited)"
    try:
        inflated = gzip.decompress(gz)
    except (OSError, EOFError) as exc:
        return False, f"the stored bytes are not a valid gzip stream ({exc})"
    raw = SRC.read_bytes()
    if inflated != raw:
        return False, (f"inflates to {len(inflated):,} bytes, but "
                       f"{SRC.name} is now {len(raw):,} bytes")
    return True, f"{len(gz):,} stored bytes inflate to {len(raw):,} bytes, byte-identical"


def main() -> int:
    if not SRC.is_file():
        print(f"error: {SRC} not found")
        return 2

    ok, detail = committed_is_current()

    if "--check" in sys.argv:
        if ok:
            print(f"OK: {OUT.relative_to(ROOT)} — {detail}")
            return 0
        print(f"FAIL: {OUT.relative_to(ROOT)} is stale — {detail}.\n"
              f"  Run: python3 scripts/gen_failsafe.py")
        return 1

    if ok and "--force" not in sys.argv:
        print(f"up to date: {OUT.relative_to(ROOT)} — {detail}")
        return 0

    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if _PIO:
    main()          # pre-build hook: regenerate before anything compiles
elif __name__ == "__main__":
    sys.exit(main())
