#!/usr/bin/env python3
"""
tools/build_node_portal.py — build the node's setup page into a C header.

    node_portal/index.html  ┐
    node_portal/style.css   ├─ inline → minify → gzip -9 → src/nodecfg/NodePortalPage.h
    node_portal/app.js      ┘

Both node firmwares (node/ on the ESP8266, node_espnow/ on the XIAO C3) serve
the result at GET / with Content-Encoding: gzip (docs/NODE_CONFIG.md §6).
Neither has a filesystem holding a web tree the way the collector does, so
the page is linked into the image; one self-contained file is the only shape
that works from an AP with no internet.

MINIFICATION IS CONSERVATIVE, ON PURPOSE
  * HTML and CSS go through the same minify_html()/minify_css() that
    tools/build_web.py uses for the collector's www/ tree.
  * JavaScript only loses whole-line // comments, indentation and blank
    lines. No parser is involved, so nothing that could change what the code
    means is attempted — the same line tools/build_web.py draws. app.js is
    ES5 without template literals, so a line cannot start inside a string.

THE HEADER IS COMMITTED, AND COMPARED BY CONTENT
  The Arduino IDE path runs no pre-build scripts, so a generated-only header
  would break that build. Staleness is judged by INFLATING the committed
  bytes and comparing them with a fresh in-memory build — never by comparing
  compressed bytes, which differ between zlib and zlib-ng for the same input
  (scripts/gen_failsafe.py learned this first). For the same reason the
  header is only rewritten when it is stale, so re-running is a no-op.

Usage:
    python3 tools/build_node_portal.py           # rebuild if stale, print size
    python3 tools/build_node_portal.py --force   # rebuild unconditionally
    python3 tools/build_node_portal.py --check   # exit 1 if stale
"""
from __future__ import annotations

import gzip
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "node_portal"
OUT = ROOT / "src" / "nodecfg" / "NodePortalPage.h"
BUDGET = 20 * 1024  # §6: under 20 KB gzipped

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_web import minify_css, minify_html  # noqa: E402


def _read(name: str) -> str:
    # LF-normalised, so a Windows checkout (core.autocrlf) builds the same page.
    return (SRC / name).read_bytes().decode("utf-8").replace("\r\n", "\n")


def minify_js(src: str) -> str:
    out = []
    for line in src.split("\n"):
        s = line.strip()
        if not s or s.startswith("//"):
            continue
        out.append(s)
    return "\n".join(out) + "\n"


def build_html() -> bytes:
    """The page exactly as the node serves it (before gzip)."""
    html = minify_html(_read("index.html"))
    css = minify_css(_read("style.css")).strip()
    js = minify_js(_read("app.js")).strip()
    if "</script" in js.lower() or "</style" in css.lower():
        raise SystemExit("error: a closing </script> or </style> inside the source would end the inlined block")
    link = '<link rel="stylesheet" href="style.css">'
    script = '<script src="app.js"></script>'
    if html.count(link) != 1 or html.count(script) != 1:
        raise SystemExit(f"error: index.html must reference style.css and app.js exactly once as\n  {link}\n  {script}")
    html = html.replace(link, "<style>" + css + "</style>")
    html = html.replace(script, "<script>" + js + "</script>")
    return html.encode("utf-8")


def compress(raw: bytes) -> bytes:
    # mtime=0: the output depends only on the input.
    return gzip.compress(raw, compresslevel=9, mtime=0)


def render_header(raw: bytes, gz: bytes) -> str:
    rows = []
    for i in range(0, len(gz), 16):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in gz[i:i + 16]))
    return f"""// ============================================================================
// src/nodecfg/NodePortalPage.h — GENERATED by tools/build_node_portal.py.
// Do not edit: change node_portal/{{index.html,style.css,app.js}} and rerun it.
//
// Page:   {len(raw):,} bytes inlined + minified, sha256 {hashlib.sha256(raw).hexdigest()[:16]}
// Stored: {len(gz):,} bytes gzip -9
//
// The node's own setup page (docs/NODE_CONFIG.md §6), shared by node/ and
// node_espnow/. Serve NODE_PORTAL_GZ as-is at GET / with
//   Content-Type: text/html; charset=utf-8
//   Content-Encoding: gzip
// ============================================================================
#pragma once

#include <stdint.h>
#include <stddef.h>
#if defined(ARDUINO)
#  include <pgmspace.h>
#endif
#ifndef PROGMEM
#  define PROGMEM
#endif

static const uint8_t NODE_PORTAL_GZ[] PROGMEM = {{
{chr(10).join(rows)}
}};

static const size_t NODE_PORTAL_GZ_LEN = sizeof(NODE_PORTAL_GZ);
"""


_BYTES_RE = re.compile(r"NODE_PORTAL_GZ\[\]\s*PROGMEM\s*=\s*\{(.*?)\};", re.S)


def committed_payload() -> bytes:
    if not OUT.is_file():
        return b""
    m = _BYTES_RE.search(OUT.read_text(encoding="utf-8"))
    if not m:
        return b""
    return bytes(int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", m.group(1)))


def committed_is_current(raw: bytes) -> tuple[bool, str]:
    gz = committed_payload()
    if not gz:
        return False, "no NODE_PORTAL_GZ array (header missing or edited)"
    try:
        got = gzip.decompress(gz)
    except (OSError, EOFError) as exc:
        return False, f"the stored bytes are not a valid gzip stream ({exc})"
    if got != raw:
        return False, f"inflates to {len(got):,} bytes, the sources build {len(raw):,}"
    return True, f"{len(gz):,} stored bytes inflate to the {len(raw):,}-byte page"


def main(argv: list[str]) -> int:
    raw = build_html()
    ok, detail = committed_is_current(raw)
    rel = OUT.relative_to(ROOT)
    if "--check" in argv:
        if ok:
            print(f"OK: {rel} — {detail}")
            return 0
        print(f"FAIL: {rel} is stale — {detail}.\n  Run: python3 tools/build_node_portal.py")
        return 1
    gz = compress(raw)
    if not ok or "--force" in argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(render_header(raw, gz), encoding="utf-8", newline="\n")
        print(f"wrote {rel}")
    else:
        print(f"up to date: {rel}")
    print(f"page {len(raw):,} bytes → {len(gz):,} bytes gzipped "
          f"({len(gz) / 1024:.1f} KB of the {BUDGET // 1024} KB budget)")
    if len(gz) > BUDGET:
        print(f"error: over the {BUDGET // 1024} KB budget (docs/NODE_CONFIG.md §6)")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
